name: Build obfuscator-llvm

on:
  push:
    branches:
      - main  # 可以修改为你的主要分支
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # 使用 Ubuntu 最新环境构建

    steps:
    # Step 1: 检出代码
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: 安装依赖
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          clang \
          python3 \
          git

    # Step 3: 克隆 obfuscator 仓库，并检出特定分支
    - name: Clone obfuscator-llvm repository
      run: |
        git clone -b llvm-4.0 https://github.com/obfuscator-llvm/obfuscator.git
        cd obfuscator
        git submodule update --init --recursive

    # Step 4: 创建构建目录
    - name: Create build directory
      run: mkdir -p obfuscator/build

    # Step 5: 使用 cmake 配置构建
    - name: Run cmake
      run: |
        cd obfuscator/build
        cmake -DCMAKE_BUILD_TYPE=Release ../

    # Step 6: 执行构建
    - name: Build the project
      run: |
        cd obfuscator/build
        make -j7

    # Step 7: 安装编译产物
    - name: Install obfuscator-llvm
      run: |
        cd obfuscator/build
        sudo make install

    # Step 8: 验证是否安装成功
    - name: Verify Installation
      run: |
        obfuscator-llvm --version
