name: Build obfuscator-llvm

# 控制何时触发此工作流
on:
  push:
    branches:
      - main  # 你可以选择你希望触发构建的分支
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # 运行环境使用最新的 Ubuntu

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # 获取代码仓库

    - name: Set up dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          clang \
          python3 \
          git

    - name: Clone obfuscator-llvm repository
      run: |
        git clone --recursive https://github.com/obfuscator-llvm/obfuscator.git
        cd obfuscator
        git submodule update --init --recursive

    - name: Build obfuscator-llvm
      run: |
        mkdir -p obfuscator/build
        cd obfuscator/build
        cmake ..
        make
        sudo make install

    - name: Verify Installation
      run: |
        # 验证 obfuscator 是否已正确安装
        obfuscator-llvm --version
